name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Install deps
        run: npm ci
      - name: Build Action
        run: npm run build
      - name: Distribute
        uses: teunmooij/github-versioned-release@v1.2.1
        with:
          template: javascript-action
        env:
          GITHUB_TOKEN: ${{ github.token }}
